### ISSUE TITLE
bin/setup takes route of CI on local machine

### ISSUE THREAD

**Issue by mhelmetag** [thoughtbot/formulator#23]
So when running `bin/setup` on my local machine, I get:
```sh
maxhelmetag:formulator/ (master) $ bin/setup
Removing previous build artifacts
bin/setup: line 9: asdf: command not found
```

This is the path of, what I think is the CI setup, running on my local machine:
```sh
if [ -z "$CI" ]; then
  echo "Removing previous build artifacts"
  rm -rf deps _build
  asdf install
fi
```

I think `if [ -z "$CI" ]; then` should be `if [ -n "$CI" ]; then` because I want this path to run anytime `$CI` is defined (and in all other instances, I don't).

Or am I missing something?

**Comment by drapergeek** [comment]
Thanks for the issue!

The script actually works as we want. If we're running it locally, the intention is to completely remove previous build artifacts and to use asdf. The primary reason we're doing this is to make sure that when we run `bin/setup` it completely resets out local environment.

Does that make sense?

**Comment by mhelmetag** [comment]
Ah okay! That makes sense. I just didn't see anywhere that said asdf was a Dev dependency so I got a bit confused when running the script.

Thanks!

**Comment by drapergeek** [comment]
In fairness it's not _really_ a requirement. You can definitely not use `asdf` that's just our preferred way of making sure we're all running the same ruby.

I'd be happy to take a PR that checked for asdf and ignored it if that's not your preferred way of handling versions.

**Comment by mhelmetag** [comment]
Either (keeping it as is or the PR to remove the dependency) seems fine. I'll just stick with `mix deps.get`. All set up now so no complaints here 😄 .
