### ISSUE TITLE
Broken for @conn based forms

### ISSUE THREAD

**Issue by jsteiner** [thoughtbot/formulator#25]
When you [define a form with connection data](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Form.html#module-with-connection-data) (i.e. `<%= form_for @conn`, Formulator now fails as it expects a `validations` key in the `source`, but a connection does not have validations.

The failure happens on [this line](https://github.com/thoughtbot/formulator/blob/f842594324d78fbd65327b83bb5c773b37590afb/lib/formulator.ex#L156)

**Comment by dbernheisel** [comment]
I've replicated this. Should be fixed by #26.

**Comment by dbernheisel** [comment]
Fix was released with v0.1.7.
