### ISSUE TITLE
Logo proposal 

### ISSUE THREAD

**Issue by reallinfo** [thoughtbot/formulator#40]
Hello! I am a graphic designer. I want to contribute to Formulator. Do you want me to design a logo for the formulator?  If you have an idea, you can say me.

**Comment by drapergeek** [comment]
Hi @reallinfo if you'd like to contribute we'd be happy to display a logo. I don't have anything in mind so run with your creativity!

**Comment by reallinfo** [comment]
![formulator](https://user-images.githubusercontent.com/36298335/40589730-686d4534-61fb-11e8-9efb-1a24afbcc353.jpg)

Sure.
I combined a phoneix logo and form icon. What do you think?

**Comment by reallinfo** [comment]
Thank you @dbernheisel 

What do you think? @drapergeek

**Comment by reallinfo** [comment]
Oh, pardon.  Maybe.

that's why, I designed something that would remind of phoenix. How is these?

![formulator2](https://user-images.githubusercontent.com/36298335/40676737-5310a19c-6384-11e8-859a-a346595cc765.jpg)

**Comment by drapergeek** [comment]
I think I prefer the last option there with the shadows.

**Comment by dbernheisel** [comment]
Heyo! This is around 3 years old now. I enjoy the logo and really appreciate the work you put into this 3 years ago. I don't have a strong opinion on having a logo for this little ol' library, so for now I'm going to close this PR. If you're using Formulator and want the logo to contributed, I would be happy to consider it again (and this time, we'd merge it :)

For the sake of cleaning up PRs and issues. I'll close this for now.
