### ISSUE TITLE
`field`?

### ISSUE THREAD

**Issue by drapergeek** [thoughtbot/formulator#8]
Moving forward, to support other inputs such as `radio_button` or `select`, the logic for switching based on those in the `input` function is going to get pretty messy.

It seems like instead, we should break out multiple functions for those but the `select` and `radio_button` are already taken.

What do you all think about using `field` as the name for our inputs. We could go with `field` to replace `input` and you can still use `field(form, :phone, as: :number)` if you wanted to. We could then add `select_field(form, :state, state_options)` and others.

I'd love any thoughts you have @anellis @jsteiner

**Comment by jsteiner** [comment]
@drapergeek we already have an `input_function` which switches on `textarea`s. Will there be any additional logic aside from adding a few more conditions to that function?

**Comment by drapergeek** [comment]
For the `select` function, we need to take in a collection and I don't think it's ideal to pass that in to the `options` list, so we'd need a new arity.

If we did keep it in the options, then we'd have more branching logic for extracting the specific options.

**Comment by jsteiner** [comment]
Seems reasonable to me. I wonder if we even need `field`. If we don't plan on inferring types, I'd rather do `number_field` than `field(..., as: :number)`.

**Comment by anellis** [comment]
My initial thought would be that if it's easier for the user to have one `input` then it seems silly to avoid it just to save ourselves from conditionals. I could be convinced that having to call the specific type of field that you want is less magical and would be less confusing but I feel like the convenience of having it infer the type for you is nice

**Comment by dbern-stripe** [comment]
Closing out old issues.
